# Generated by Django 5.1.7 on 2025-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_materialrestockrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=50),
        ),
    ]
