# Generated by Django 5.1.7 on 2025-04-14 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_rv', '0003_alter_draftpurchaseorder_restocking_request'),
        ('warehouse', '0004_restockitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrestockrequest',
            name='draft_po',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_request', to='po_rv.draftpurchaseorder'),
        ),
    ]
