# Generated by Django 5.1.7 on 2025-04-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_materialrestockrequest_draft_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrestockrequest',
            name='request_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
