# Generated by Django 5.1.7 on 2025-04-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_materialrestockrequest_request_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrestockrequest',
            name='draft_po',
        ),
    ]
