# Generated by Django 5.1.7 on 2025-04-17 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0006_materialrestockrequest_request_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rv_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requisition_vouchers/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_vouchers', to='warehouse.materialrestockrequest')),
            ],
        ),
    ]
