# Generated by Django 5.1.7 on 2025-04-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_purchaseorder_comments_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftreceivingvoucher',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='restocking_request',
        ),
        migrations.RemoveField(
            model_name='receivingvoucher',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='DraftPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='DraftReceivingVoucher',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='ReceivingVoucher',
        ),
    ]
