# Generated by Django 5.1.7 on 2025-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_rv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
    ]
