# Generated by Django 5.1.7 on 2025-04-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_rv', '0002_purchaseorder_status'),
        ('warehouse', '0004_restockitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpurchaseorder',
            name='restocking_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='warehouse.materialrestockrequest'),
        ),
    ]
