# Generated by Django 5.1.7 on 2025-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_rv', '0003_alter_draftpurchaseorder_restocking_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpurchaseorder',
            name='fillable_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
