# Generated by Django 5.1.7 on 2025-04-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_rv', '0004_draftpurchaseorder_fillable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingvoucher',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='DraftReceivingVoucher',
        ),
        migrations.DeleteModel(
            name='ReceivingVoucher',
        ),
    ]
