# Generated by Django 5.1.7 on 2025-04-24 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_rv', '0005_remove_receivingvoucher_purchase_order_and_more'),
        ('warehouse', '0007_remove_materialrestockrequest_draft_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='address',
            field=models.TextField(default='Supplier Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rv_number',
            field=models.CharField(default='Default RV Number', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='restocking_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='warehouse.materialrestockrequest'),
        ),
        migrations.DeleteModel(
            name='DraftPurchaseOrder',
        ),
    ]
